"""Immutable private storage. Keys are generated by the backend, never callers."""

import hashlib
import os
from pathlib import Path, PurePosixPath
from uuid import uuid4


def digest(data):
    return hashlib.sha256(data).hexdigest()


class Storage:
    def __init__(self, root):
        self.root = Path(root).absolute()
        if self.root.is_symlink():
            raise ValueError("symlink storage root")
        self.root.mkdir(mode=0o700, parents=True, exist_ok=True)

    def read(self, key, expected=None):
        parts = PurePosixPath(key).parts
        if not parts or any(p in (".", "..", "/") for p in parts):
            raise ValueError("invalid storage key")
        fd = os.open(self.root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        try:
            for part in parts[:-1]:
                child = os.open(
                    part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=fd
                )
                os.close(fd)
                fd = child
            file_fd = os.open(parts[-1], os.O_RDONLY | os.O_NOFOLLOW, dir_fd=fd)
            with os.fdopen(file_fd, "rb") as stream:
                content = stream.read()
        finally:
            os.close(fd)
        if expected is not None and digest(content) != expected:
            raise ValueError("artifact_corrupt")
        return content

    def put(self, content):
        key = uuid4().hex
        staging = self.root / ("." + key + ".staging")
        with staging.open("xb") as stream:
            os.chmod(staging, 0o600)
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.link(staging, self.root / key)
        staging.unlink()
        fd = os.open(self.root, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(fd)
        finally:
            os.close(fd)
        return key, digest(content), len(content)
